name: Deploy to Xserver

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Deploy to Xserver via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: aquabit-lab.com/public_html/
        log-level: verbose
        dangerous-clean-slate: true
        timeout: 600000
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.php
          **/.DS_Store
          **/README.md
          **/.github/**
          
    - name: Create htaccess and verify deployment
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        lftp -c '
        set ftp:ssl-allow no;
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
        cd aquabit-lab.com/public_html/;
        ls -la;
        echo "DirectoryIndex index.html index.php" > .htaccess;
        echo "" >> .htaccess;
        echo "# RewriteEngine On" >> .htaccess;
        echo "# RewriteRule ^old-page$ /new-page [R=301,L]" >> .htaccess;
        ls -la;
        quit
        '