name: Deploy to Xserver

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List files to be deployed
      run: |
        echo "=== Files to be deployed ==="
        ls -la
        echo "=== HTML files ==="
        find . -name "*.html" -type f
        
    - name: Deploy to Xserver via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /
        log-level: verbose
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.php
          **/.DS_Store
          **/README.md