name: Test Multiple Deploy Paths

on:
  workflow_dispatch:

jobs:
  test-path-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Deploy to public_html
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: public_html
        log-level: verbose
        exclude: |
          **/.git*
          **/*.php
          **/README.md

  test-path-2:
    runs-on: ubuntu-latest
    needs: test-path-1
    steps:
    - uses: actions/checkout@v4
    - name: Test Deploy to /public_html/
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        log-level: verbose
        exclude: |
          **/.git*
          **/*.php
          **/README.md